/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rhythm;

import model.Pattern;
import model.PatternSequence;
import model.MidiEvent;
import model.MidiInstrument;
import misc.UsbWriter;
import java.awt.Color;
import java.awt.Component;
import java.awt.Point;
import static java.awt.event.MouseEvent.BUTTON1;
import static java.awt.event.MouseEvent.BUTTON3;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.FileFilter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import static javax.swing.SwingConstants.CENTER;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableCellRenderer;
import misc.ComboBoxRenderer;

/**
 *
 * @author Tomek
 */
public class MainFrame extends javax.swing.JFrame {
    private final boolean usbResult;
    public static PatternSequence currentSequence;
    public static Pattern currentPattern;
    private List<Pattern> patternList;
    private MidiEvent currentEvent;
    private int currentNote;
    private int currentOctave;
    private boolean togglePlayback;
    private Playback patternPlayback;
    private Playback sequencePlayback;
    private FileReaderWriter rhythmFileRW;
    private RhythmUsbSender sender;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {        
        initComponents();
        usbResult = UsbWriter.init("COM4","Rhythm");
        currentSequence = new PatternSequence();
        patternList = new ArrayList();
        setRhythmTableModel();
        togglePlayback  = false;
        currentNote =  0; // 24 = C contra
        currentOctave = 0;
        rhythmFileRW = new FileReaderWriter(new File("plik.bin"));
        ((RhythmPanel)rhythmPanel).setInstrumentIndex(instrumentComboBox.getSelectedIndex());
        ((RhythmPanel)rhythmPanel).setCurrentNoteIndex(noteSelectComboBox.getSelectedIndex());
        ((RhythmPanel)rhythmPanel).setCurrentOctaveIndex(octaveSelectComboBox.getSelectedIndex());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insertPatternPopup = new javax.swing.JPopupMenu();
        choosePattern = new javax.swing.JMenuItem();
        removePattern = new javax.swing.JMenuItem();
        insertOneBefore = new javax.swing.JMenuItem();
        insertOneAfter = new javax.swing.JMenuItem();
        clearSequence = new javax.swing.JMenuItem();
        drumPatternLabel = new javax.swing.JLabel();
        paneSeparator = new javax.swing.JSeparator();
        sequenceScrollPane = new javax.swing.JScrollPane();
        sequenceTable = new JSequenceTable();
        saveSequenceButton = new javax.swing.JButton();
        leftHandLabel = new javax.swing.JLabel();
        rightHandLabel = new javax.swing.JLabel();
        leftFootLabel = new javax.swing.JLabel();
        rightFootLabel = new javax.swing.JLabel();
        bassGuitarLabel = new javax.swing.JLabel();
        playSequenceButton = new javax.swing.JButton();
        saveFileButton = new javax.swing.JButton();
        selectSequencePatternComboBox = new JPatternComboBox();
        repeatPatternSpinner = new javax.swing.JSpinner();
        setPatternButton = new javax.swing.JButton();
        usbTransferButton = new javax.swing.JButton();
        progressLabel = new javax.swing.JLabel();
        rhythmPanel = new RhythmPanel();
        patternGroupPanel = new javax.swing.JPanel();
        playPatternButton = new javax.swing.JButton();
        divisionComboBox = new javax.swing.JComboBox<>();
        timeSpinner = new javax.swing.JSpinner();
        savePatternButton = new javax.swing.JButton();
        selectPatternComboBox = new JPatternComboBox();
        selectPatternLabel = new javax.swing.JLabel();
        numberOfBeats = new javax.swing.JComboBox<>();
        instrumentComboBox = new javax.swing.JComboBox<>();
        beatLabel = new javax.swing.JLabel();
        instrumentLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        resolutionLabel = new javax.swing.JLabel();
        noteSelectComboBox = new javax.swing.JComboBox<>();
        noteLabel = new javax.swing.JLabel();
        octaveLabel = new javax.swing.JLabel();
        octaveSelectComboBox = new javax.swing.JComboBox<>();
        clearPatternButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileMenuOpen = new javax.swing.JMenuItem();
        fileMenuAdd = new javax.swing.JMenuItem();
        fileMenuClose = new javax.swing.JMenuItem();
        fileMenuSave = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();

        choosePattern.setText("Choose pattern");
        choosePattern.setActionCommand("choosePattern");
        choosePattern.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choosePatternMouseClicked(evt);
            }
        });
        choosePattern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePatternActionPerformed(evt);
            }
        });
        insertPatternPopup.add(choosePattern);

        removePattern.setText("Clear pattern");
        removePattern.setActionCommand("removePattern");
        removePattern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePatternActionPerformed(evt);
            }
        });
        insertPatternPopup.add(removePattern);

        insertOneBefore.setText("Insert empty before");
        insertOneBefore.setActionCommand("insertPatternBefore");
        insertOneBefore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertOneBeforeActionPerformed(evt);
            }
        });
        insertPatternPopup.add(insertOneBefore);

        insertOneAfter.setText("Insert empty after");
        insertOneAfter.setActionCommand("insertOneAfter");
        insertOneAfter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertOneAfterActionPerformed(evt);
            }
        });
        insertPatternPopup.add(insertOneAfter);

        clearSequence.setText("Clear sequence");
        clearSequence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSequenceActionPerformed(evt);
            }
        });
        insertPatternPopup.add(clearSequence);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        drumPatternLabel.setText("Current drum pattern");

        sequenceTable.setTableHeader(null);
        sequenceTable.setShowGrid(true);
        sequenceTable.setColumnSelectionAllowed(false);
        sequenceTable.setRowSelectionAllowed(false);
        sequenceTable.setRequestFocusEnabled(false);
        sequenceTable.setCellSelectionEnabled(false);
        sequenceTable.setDefaultRenderer(Object.class, new CustomCellRenderer());
        sequenceTable.setDefaultEditor(Object.class, null);
        sequenceTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sequenceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sequenceTable.setAutoscrolls(false);
        sequenceTable.setFocusable(false);
        sequenceTable.setGridColor(new java.awt.Color(0, 0, 0));
        sequenceTable.setName("sequenceTable"); // NOI18N
        sequenceTable.setOpaque(false);
        sequenceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sequenceTableMouseClicked(evt);
            }
        });
        sequenceScrollPane.setViewportView(sequenceTable);

        saveSequenceButton.setText("Save sequence");
        saveSequenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSequenceButtonActionPerformed(evt);
            }
        });

        leftHandLabel.setText("Left hand");

        rightHandLabel.setText("Right hand");

        leftFootLabel.setText("Left foot");

        rightFootLabel.setText("Right foot");

        bassGuitarLabel.setText("Bass guitar");

        playSequenceButton.setText("Play sequence");
        playSequenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSequenceButtonActionPerformed(evt);
            }
        });

        saveFileButton.setText("Save file");
        saveFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileButtonActionPerformed(evt);
            }
        });

        selectSequencePatternComboBox.setEnabled(false);
        selectSequencePatternComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectSequencePatternComboBoxItemStateChanged(evt);
            }
        });
        selectSequencePatternComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectSequencePatternComboBoxMouseClicked(evt);
            }
        });
        selectSequencePatternComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSequencePatternComboBoxActionPerformed(evt);
            }
        });

        repeatPatternSpinner.setEnabled(false);
        repeatPatternSpinner.setValue(1);
        repeatPatternSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                repeatPatternSpinnerStateChanged(evt);
            }
        });

        setPatternButton.setText("OK");
        setPatternButton.setEnabled(false);
        setPatternButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setPatternButtonMouseClicked(evt);
            }
        });
        setPatternButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPatternButtonActionPerformed(evt);
            }
        });

        usbTransferButton.setText("Send via USB");
        usbTransferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usbTransferButtonActionPerformed(evt);
            }
        });

        progressLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        rhythmPanel.setLayout(new java.awt.GridLayout(5, 4));

        patternGroupPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        patternGroupPanel.setName(""); // NOI18N

        playPatternButton.setText("Play pattern");
        playPatternButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playPatternButtonActionPerformed(evt);
            }
        });

        divisionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32" }));
        divisionComboBox.setName("divisionComboBox"); // NOI18N
        divisionComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                divisionComboBoxItemStateChanged(evt);
            }
        });
        divisionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionComboBoxActionPerformed(evt);
            }
        });

        timeSpinner.setValue(60);
        timeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                timeSpinnerStateChanged(evt);
            }
        });
        timeSpinner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeSpinnerMouseClicked(evt);
            }
        });

        savePatternButton.setText("Save pattern");
        savePatternButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savePatternButtonMouseClicked(evt);
            }
        });
        savePatternButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePatternButtonActionPerformed(evt);
            }
        });

        selectPatternComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "New" }));
        selectPatternComboBox.setName("selectPatternComboBox"); // NOI18N
        selectPatternComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectPatternComboBoxItemStateChanged(evt);
            }
        });
        selectPatternComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectPatternComboBoxMouseClicked(evt);
            }
        });
        selectPatternComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPatternComboBoxActionPerformed(evt);
            }
        });

        selectPatternLabel.setText("Select pattern");

        numberOfBeats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        numberOfBeats.setSelectedIndex(3);
        numberOfBeats.setName("numberOfBeats"); // NOI18N
        numberOfBeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfBeatsActionPerformed(evt);
            }
        });

        instrumentComboBox.setModel(new javax.swing.DefaultComboBoxModel<String>(model.MidiInstrument.displayValues()));
        instrumentComboBox.setOpaque(false);
        instrumentComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                instrumentComboBoxItemStateChanged(evt);
            }
        });
        instrumentComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                instrumentComboBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                instrumentComboBoxPopupMenuWillBecomeVisible(evt);
            }
        });
        instrumentComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instrumentComboBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                instrumentComboBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                instrumentComboBoxMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                instrumentComboBoxMouseReleased(evt);
            }
        });
        instrumentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instrumentComboBoxActionPerformed(evt);
            }
        });

        beatLabel.setText("Beats");

        instrumentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instrumentLabel.setText("Instrument");
        instrumentLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        instrumentLabel.setOpaque(true);

        timeLabel.setText("Time");

        resolutionLabel.setText("Division");

        noteSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "C#/Db", "D", "D#/Eb", "E", "E#/F", "F#/Gb", "G", "G#/Ab", "A", "A#/Bb", "B", "B#/C" }));
        noteSelectComboBox.setEnabled(false);
        noteSelectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteSelectComboBoxActionPerformed(evt);
            }
        });

        noteLabel.setText("Note");

        octaveLabel.setText("Octave");

        octaveSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contra", "Great", "Small", "1 Line", "2 Line", "3 Line", "4 Line", "5 Line", "6 Line" }));
        octaveSelectComboBox.setEnabled(false);
        octaveSelectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octaveSelectComboBoxActionPerformed(evt);
            }
        });

        clearPatternButton.setText("Clear pattern");
        clearPatternButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPatternButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patternGroupPanelLayout = new javax.swing.GroupLayout(patternGroupPanel);
        patternGroupPanel.setLayout(patternGroupPanelLayout);
        patternGroupPanelLayout.setHorizontalGroup(
            patternGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patternGroupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patternGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patternGroupPanelLayout.createSequentialGroup()
                        .addGroup(patternGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instrumentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instrumentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(patternGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(beatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberOfBeats, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(patternGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(divisionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resolutionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(patternGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(patternGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectPatternComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectPatternLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(patternGroupPanelLayout.createSequentialGroup()
                        .addComponent(noteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noteSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(octaveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(octaveSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24)
                .addComponent(clearPatternButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savePatternButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playPatternButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        patternGroupPanelLayout.setVerticalGroup(
            patternGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patternGroupPanelLayout.createSequentialGroup()
                .addGroup(patternGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectPatternLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resolutionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instrumentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(patternGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrumentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOfBeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectPatternComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearPatternButton)
                    .addComponent(savePatternButton)
                    .addComponent(playPatternButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(patternGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noteLabel)
                    .addComponent(noteSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(octaveLabel)
                    .addComponent(octaveSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        fileMenu.setText("File");

        fileMenuOpen.setText("Open rhythm");
        fileMenuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuOpenActionPerformed(evt);
            }
        });
        fileMenu.add(fileMenuOpen);

        fileMenuAdd.setText("Add rhythm");
        fileMenuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuAddActionPerformed(evt);
            }
        });
        fileMenu.add(fileMenuAdd);

        fileMenuClose.setText("Close rhythm");
        fileMenuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuCloseActionPerformed(evt);
            }
        });
        fileMenu.add(fileMenuClose);

        fileMenuSave.setText("Save rhythm");
        fileMenuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuSaveActionPerformed(evt);
            }
        });
        fileMenu.add(fileMenuSave);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");
        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneSeparator)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leftHandLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rightHandLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leftFootLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rightFootLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bassGuitarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(drumPatternLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 800, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(patternGroupPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sequenceScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(playSequenceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(saveSequenceButton)
                                            .addGap(18, 18, 18)
                                            .addComponent(saveFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addComponent(progressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(usbTransferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addComponent(selectSequencePatternComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(repeatPatternSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(124, 124, 124)
                                            .addComponent(setPatternButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(rhythmPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drumPatternLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(leftHandLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightHandLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(leftFootLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightFootLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bassGuitarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rhythmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(patternGroupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(paneSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playSequenceButton)
                    .addComponent(saveSequenceButton)
                    .addComponent(saveFileButton)
                    .addComponent(usbTransferButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectSequencePatternComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(repeatPatternSpinner)
                            .addComponent(setPatternButton))
                        .addGap(18, 18, 18)
                        .addComponent(progressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addComponent(sequenceScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        patternGroupPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileMenuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuOpenActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "Rhythm bin files", "bin");
        chooser.addChoosableFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            File currentFile = chooser.getSelectedFile();
            rhythmFileRW.setFile(currentFile);
            patternList.clear();
            currentSequence.getPatternList().clear();
            Object[] objects = rhythmFileRW.readPatterns();
            patternList = (List<Pattern>)objects[0];
            currentSequence = (PatternSequence)objects[1];
            Pattern.setGlobalID(currentSequence.getPatternList().size());
                       
            
            for(int index = 0; index < currentSequence.getPatternList().size(); index++){
                int x = index / sequenceTable.getColumnCount(); // row
                int y = index % sequenceTable.getColumnCount(); // column  
                ((JSequenceTable)sequenceTable).setCurrentColumn(y);
                ((JSequenceTable)sequenceTable).setCurrentRow(x);
                ((JSequenceTable)sequenceTable).insertPattern();
            }
            String[] array = new String[patternList.size() + 1];
            for (int i = 0; i < patternList.size(); i++) {
                array[i] = patternList.get(i).toString();
            }
            array[patternList.size()] = "New";
            selectPatternComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(array));
            
            // pattern list without New item
            String[] patterns = new String[patternList.size()];        
            for (int i = 0; i < patternList.size(); i++) {
                patterns[i] = patternList.get(i).toString();
            }
            selectSequencePatternComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(patterns));
            
            // set first pattern from combo box as current one
            selectPatternComboBoxActionPerformed(null);
        }
    }//GEN-LAST:event_fileMenuOpenActionPerformed

    private void fileMenuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuCloseActionPerformed
    
    private void savePatternButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePatternButtonActionPerformed
        
    }//GEN-LAST:event_savePatternButtonActionPerformed

    private void saveSequenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSequenceButtonActionPerformed
//        Query query = em.createNamedQuery("Song.findAll");        
//        Collection songs = query.getResultList();
//        System.out.println(songs);
//        Pattern p = new Pattern();
//        int beatTime = 60000 / Integer.parseInt(timeSpinner.getValue().toString());
//        int beats = Integer.parseInt(numberOfBeats.getSelectedItem().toString());
//        int div = Integer.parseInt(divisionComboBox.getSelectedItem().toString());
//        int subBeats = beats * div;
//        int barDuration = beats * beatTime;
//        p.setBeats(subBeats);
//        p.setBeatTime(barDuration);
//        PatternSequence sequence = new PatternSequence();
//        em.getTransaction().begin();
//        em.persist(p);
//        List patterns = new ArrayList();
//        patterns.add(p);
//        sequence.setPatternList(patterns); 
//        em.persist(sequence); 
//        em.getTransaction().commit();
        //new Controller(em).savePattern(p);
    }//GEN-LAST:event_saveSequenceButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void divisionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionComboBoxActionPerformed
        Pattern tmp = currentPattern;
        changeRhythmTableModel();
        currentPattern.setID(tmp.getID());
        if(patternPlayback != null)
            patternPlayback.setTime(Integer.parseInt(timeSpinner.getValue().toString()),
                    Integer.parseInt(divisionComboBox.getSelectedItem().toString()),
                    Integer.parseInt(numberOfBeats.getSelectedItem().toString()));
            
    }//GEN-LAST:event_divisionComboBoxActionPerformed

    private void divisionComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_divisionComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_divisionComboBoxItemStateChanged

    private void playPatternButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playPatternButtonActionPerformed
        if(sequencePlayback != null){
            sequencePlayback.stopExecuting();
            playSequenceButton.setText("Play pattern");
        }
        togglePlayback = !togglePlayback;
        
        if(togglePlayback == true){
            playPatternButton.setText("Stop");
            patternPlayback = new Playback(Playback.PATTERN);
            currentPattern.setBeatTime(Integer.parseInt(timeSpinner.getValue().toString()));
            currentPattern.setDivision(Integer.parseInt(divisionComboBox.getSelectedItem().toString()));
            currentPattern.setBeats(Integer.parseInt(numberOfBeats.getSelectedItem().toString()));
            patternPlayback.start();
        }
        else{
            playPatternButton.setText("Play pattern");
            patternPlayback.stopExecuting();
        }
    }//GEN-LAST:event_playPatternButtonActionPerformed

    private void playSequenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playSequenceButtonActionPerformed
        if(patternPlayback != null){
            patternPlayback.stopExecuting();
            playSequenceButton.setText("Play sequence");
        }
           
        togglePlayback = !togglePlayback;
        
        if(togglePlayback == true){
            playSequenceButton.setText("Stop");
            patternPlayback = new Playback(Playback.SEQUENCE);
            currentPattern.setBeatTime(Integer.parseInt(timeSpinner.getValue().toString()));
            currentPattern.setDivision(Integer.parseInt(divisionComboBox.getSelectedItem().toString()));
            currentPattern.setBeats(Integer.parseInt(numberOfBeats.getSelectedItem().toString()));
            patternPlayback.start();
        }
        else{
            playSequenceButton.setText("Play sequence");
            patternPlayback.stopExecuting();
        }
    }//GEN-LAST:event_playSequenceButtonActionPerformed

    private void numberOfBeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfBeatsActionPerformed
        Pattern tmp = currentPattern;
        changeRhythmTableModel();
        currentPattern.setID(tmp.getID());
        if(patternPlayback != null)
            patternPlayback.setTime(Integer.parseInt(timeSpinner.getValue().toString()),
                    Integer.parseInt(divisionComboBox.getSelectedItem().toString()),
                    Integer.parseInt(numberOfBeats.getSelectedItem().toString()));
    }//GEN-LAST:event_numberOfBeatsActionPerformed

    private void instrumentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instrumentComboBoxActionPerformed
       
        MidiInstrument instrument = MidiInstrument.getInstrumentByIndex(instrumentComboBox.getSelectedIndex());
        instrumentLabel.setBackground(instrument.getBackground());
        instrumentLabel.setForeground(instrument.getForeground());
        instrumentLabel.setOpaque(true);
        
        if(instrument != MidiInstrument.BASS_GUITAR){
            this.noteSelectComboBox.setEnabled(false);
            this.octaveSelectComboBox.setEnabled(false);
        }
        else{
            this.noteSelectComboBox.setEnabled(true);
            this.octaveSelectComboBox.setEnabled(true);
        } 
        
        ((RhythmPanel)rhythmPanel).setInstrumentIndex(instrumentComboBox.getSelectedIndex());
        
    }//GEN-LAST:event_instrumentComboBoxActionPerformed

    private void selectPatternComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPatternComboBoxActionPerformed
        int index = selectPatternComboBox.getSelectedIndex();         
        if(selectPatternComboBox.getSelectedItem().toString().equals("New")){
            index = selectPatternComboBox.getSelectedIndex();            
            setRhythmTableModel(); 
        }
        
        try{
            Pattern tmp = patternList.get(index);
            Integer beats = tmp.getBeats();
            Integer division = tmp.getDivision();
            Integer duration = tmp.getBeatTime();
            divisionComboBox.setSelectedItem(division.toString());
            timeSpinner.setValue(duration);
            numberOfBeats.setSelectedItem(beats.toString());            
            currentPattern = tmp;
            
            ((RhythmPanel)rhythmPanel).setCurrentPattern(currentPattern); 
            ((RhythmPanel)rhythmPanel).makeLabels();
                       
        }catch(IndexOutOfBoundsException ex){
            System.out.println("selectPatternComboBoxActionPerformed " + ex.getMessage());
        //setRhythmTableModel();                         

        }
    }//GEN-LAST:event_selectPatternComboBoxActionPerformed

    private void timeSpinnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeSpinnerMouseClicked
        
    }//GEN-LAST:event_timeSpinnerMouseClicked

    private void timeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_timeSpinnerStateChanged
        currentPattern.setBeatTime(Integer.parseInt(timeSpinner.getValue().toString()));
        currentPattern.setDivision(Integer.parseInt(divisionComboBox.getSelectedItem().toString()));
        currentPattern.setBeats(Integer.parseInt(numberOfBeats.getSelectedItem().toString()));
    }//GEN-LAST:event_timeSpinnerStateChanged

    private void noteSelectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteSelectComboBoxActionPerformed
        currentNote = noteSelectComboBox.getSelectedIndex(); 
        ((RhythmPanel)rhythmPanel).setCurrentNoteIndex(noteSelectComboBox.getSelectedIndex());
    }//GEN-LAST:event_noteSelectComboBoxActionPerformed

    private void octaveSelectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octaveSelectComboBoxActionPerformed
        currentOctave = octaveSelectComboBox.getSelectedIndex();
        ((RhythmPanel)rhythmPanel).setCurrentOctaveIndex(octaveSelectComboBox.getSelectedIndex());
    }//GEN-LAST:event_octaveSelectComboBoxActionPerformed

    private void instrumentComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_instrumentComboBoxItemStateChanged
        
    }//GEN-LAST:event_instrumentComboBoxItemStateChanged

    private void instrumentComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instrumentComboBoxMouseClicked
       
    }//GEN-LAST:event_instrumentComboBoxMouseClicked

    private void instrumentComboBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instrumentComboBoxMouseEntered
        
    }//GEN-LAST:event_instrumentComboBoxMouseEntered

    private void instrumentComboBoxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instrumentComboBoxMouseReleased
        instrumentComboBox.setRenderer(new DefaultListCellRenderer());
    }//GEN-LAST:event_instrumentComboBoxMouseReleased

    private void instrumentComboBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instrumentComboBoxMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_instrumentComboBoxMouseExited

    private void instrumentComboBoxPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_instrumentComboBoxPopupMenuWillBecomeVisible
        instrumentComboBox.setRenderer(new ComboBoxRenderer());
    }//GEN-LAST:event_instrumentComboBoxPopupMenuWillBecomeVisible

    private void instrumentComboBoxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_instrumentComboBoxPopupMenuWillBecomeInvisible
        instrumentComboBox.setRenderer(new DefaultListCellRenderer());    
        
    }//GEN-LAST:event_instrumentComboBoxPopupMenuWillBecomeInvisible

    private void sequenceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sequenceTableMouseClicked
       Point pnt = evt.getPoint();
       int row = sequenceTable.rowAtPoint(pnt);
       int col = sequenceTable.columnAtPoint(pnt);
       int columns = sequenceTable.getColumnCount();
       int totalPatterns = ((JSequenceTable)sequenceTable).getTotalPatterns();
       int index = row * columns + col;
       Pattern p = null;
       if(index > ((JSequenceTable)sequenceTable).getTotalPatterns() || patternList.isEmpty()){
            System.out.println(index + " " + totalPatterns);
            return;
       }
       ((JSequenceTable)sequenceTable).setListIndex(index);
       ((JSequenceTable)sequenceTable).setCurrentRow(row);
       ((JSequenceTable)sequenceTable).setCurrentColumn(col);
       
       try{
            p = currentSequence.getPatternAt(index);
        }catch(IndexOutOfBoundsException ex){
            System.out.println("Index does not exist: " + index);  
       } 
       
       switch(evt.getButton()){ 
            case BUTTON1:   
                            if(p == null)
                                return;
                            p = currentSequence.getPatternAt(index);           
                            selectSequencePatternComboBox.setSelectedIndex(p.getID());
                            ((JSequenceTable)sequenceTable).setListIndex(index);
                            repeatPatternSpinner.setValue(p.getRepeat());
                            break;
            case BUTTON3:   int x = pnt.x;
                            int y = pnt.y;
                            insertPatternPopup.show(sequenceTable,x,y);
                            break; 
            }
       
               
       
    }//GEN-LAST:event_sequenceTableMouseClicked
    // add pattern to temporary internal list
    private void savePatternButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savePatternButtonMouseClicked
       int index = selectPatternComboBox.getSelectedIndex();
       
        try{
            currentPattern.setBeatTime(Integer.parseInt(timeSpinner.getValue().toString()));
            currentPattern.setBeats(Integer.parseInt(numberOfBeats.getSelectedItem().toString()));
            currentPattern.setDivision(Integer.parseInt(divisionComboBox.getSelectedItem().toString()));
            patternList.set(index,currentPattern);
        }
        catch(IndexOutOfBoundsException ex){
            System.out.println("savePatternButtonMouseClicked " + ex.getMessage());
            Pattern.incrementID();
            patternList.add(index,currentPattern);
            
        } 
        
        // pattern list with New item
        String[] array = new String[patternList.size() + 1];        
        for (int i = 0; i < patternList.size(); i++) {
            array[i] = patternList.get(i).toString();
        }
        array[patternList.size()] = "New";
        selectPatternComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(array));  
        ((JPatternComboBox)selectPatternComboBox).setSelection(index);        
        
        // pattern list without New item
        String[] patterns = new String[patternList.size()];        
        for (int i = 0; i < patternList.size(); i++) {
            patterns[i] = patternList.get(i).toString();
        }
        selectSequencePatternComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(patterns));
    }//GEN-LAST:event_savePatternButtonMouseClicked

    private void selectPatternComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectPatternComboBoxMouseClicked
        
    }//GEN-LAST:event_selectPatternComboBoxMouseClicked

    private void selectPatternComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectPatternComboBoxItemStateChanged
              
    }//GEN-LAST:event_selectPatternComboBoxItemStateChanged

    private void saveFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileButtonActionPerformed
        rhythmFileRW.writtePatterns(patternList,currentSequence);
    }//GEN-LAST:event_saveFileButtonActionPerformed

    private void fileMenuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuAddActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "RTH files", "bin", "rth");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            File currentFile = chooser.getSelectedFile();
            rhythmFileRW.setFile(currentFile);
            Object[] tmpseq = rhythmFileRW.readPatterns();
            currentSequence.getPatternList().addAll((List<Pattern>)tmpseq[0]);
            currentPattern = currentSequence.getPatternAt(0);
            setRhythmTableModel(currentPattern);            
            
        }
    }//GEN-LAST:event_fileMenuAddActionPerformed

    private void selectSequencePatternComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectSequencePatternComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_selectSequencePatternComboBoxItemStateChanged

    private void selectSequencePatternComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectSequencePatternComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selectSequencePatternComboBoxMouseClicked

    private void selectSequencePatternComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSequencePatternComboBoxActionPerformed
        int index = selectSequencePatternComboBox.getSelectedIndex();
        
    }//GEN-LAST:event_selectSequencePatternComboBoxActionPerformed

    private void repeatPatternSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_repeatPatternSpinnerStateChanged
        int val = Integer.parseInt(repeatPatternSpinner.getValue().toString());
        if(val < 1)
            repeatPatternSpinner.setValue(1);
    }//GEN-LAST:event_repeatPatternSpinnerStateChanged

    private void setPatternButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPatternButtonMouseClicked
//        try{
//            currentSequence.insertPattern(patternIndex, currentPattern);
//        }
//        catch(IndexOutOfBoundsException ex){
//            System.out.println("savePatternButtonMouseClicked " + ex.getMessage());
//            currentSequence.addPattern(patternIndex, currentPattern);
//        }
//        
//        ((JPatternComboBox)selectPatternComboBox).setSelection(patternIndex);
//        
//        int x = patternIndex / sequenceTable.getColumnCount(); // row
//        int y = patternIndex % sequenceTable.getColumnCount(); // column
//        
//        sequenceTable.setValueAt(patternIndex, x, y);
    }//GEN-LAST:event_setPatternButtonMouseClicked

    private void insertOneBeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertOneBeforeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertOneBeforeActionPerformed

    private void insertOneAfterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertOneAfterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertOneAfterActionPerformed

    private void choosePatternMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choosePatternMouseClicked
        
        
    }//GEN-LAST:event_choosePatternMouseClicked

    private void setPatternButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPatternButtonActionPerformed
        int patternIndex = selectSequencePatternComboBox.getSelectedIndex();
        int sequenceIndex = ((JSequenceTable)sequenceTable).getListIndex();
        try {
            Pattern cloned = (Pattern) patternList.get(patternIndex).copy();
            cloned.setRepeat(Integer.parseInt(repeatPatternSpinner.getValue().toString()));
            currentSequence.addPattern(sequenceIndex, cloned);
        } catch (NumberFormatException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
               
        ((JSequenceTable)sequenceTable).insertPattern();        
        selectSequencePatternComboBox.setEnabled(false);
        repeatPatternSpinner.setEnabled(false);
        setPatternButton.setEnabled(false);
    }//GEN-LAST:event_setPatternButtonActionPerformed

    private void choosePatternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePatternActionPerformed
        selectSequencePatternComboBox.setEnabled(true);
        repeatPatternSpinner.setEnabled(true);
        repeatPatternSpinner.setValue(1);
        setPatternButton.setEnabled(true);
    }//GEN-LAST:event_choosePatternActionPerformed

    private void removePatternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePatternActionPerformed
        ((JSequenceTable)sequenceTable).clearPattern();
    }//GEN-LAST:event_removePatternActionPerformed

    private void usbTransferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usbTransferButtonActionPerformed
        if(currentSequence.getNumOfBytes() == 0)
            return;
        if(usbTransferButton.getText().equals("Send via USB")){
            usbTransferButton.setText("Stop");
            sender = new RhythmUsbSender(currentSequence, progressLabel,usbTransferButton);
            sender.start();
        }
        else{
            usbTransferButton.setText("Send via USB");
            sender.setExecuting(false);
        }        
        
    }//GEN-LAST:event_usbTransferButtonActionPerformed

    private void clearPatternButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPatternButtonActionPerformed
        int events = currentPattern.getEventList().size();
        for(int i = 0; i < events; i++){
            currentPattern.addEvent(i, new MidiEvent());
        }
        ((RhythmPanel)rhythmPanel).setCurrentPattern(currentPattern);
       ((RhythmPanel)rhythmPanel).makeLabels();
    }//GEN-LAST:event_clearPatternButtonActionPerformed

    private void clearSequenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSequenceActionPerformed
        currentSequence = new PatternSequence();
    }//GEN-LAST:event_clearSequenceActionPerformed

    private void fileMenuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuSaveActionPerformed
        JFrame parentFrame = new JFrame();
 
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify a file to save"); 
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Rhythm bin files", "bin"));
        int userSelection = fileChooser.showSaveDialog(parentFrame);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            System.out.println("Save as file: " + fileToSave.getAbsolutePath());
            rhythmFileRW.setFile(fileToSave);
            rhythmFileRW.writtePatterns(patternList,currentSequence);
}
    }//GEN-LAST:event_fileMenuSaveActionPerformed
    
        
    private void setRhythmTableModel(Pattern tmp){
        if(tmp == null)
            return;
        
        Integer beats = tmp.getBeats();
        Integer division = tmp.getDivision();
        Integer beatTime = tmp.getBeatTime();
        divisionComboBox.setSelectedItem(division.toString());
        timeSpinner.setValue(beatTime);
        numberOfBeats.setSelectedItem(beats.toString());        
        currentPattern = tmp;       
       currentPattern.setBeats(beats);
       currentPattern.setDivision(division);
       currentPattern.setBeatTime(beatTime);
       ((RhythmPanel)rhythmPanel).setCurrentPattern(currentPattern);
       ((RhythmPanel)rhythmPanel).makeLabels();
    }   
    
    private void changeRhythmTableModel(){
        int division = Integer.parseInt(divisionComboBox.getSelectedItem().toString());
        int beats = Integer.parseInt(numberOfBeats.getSelectedItem().toString());
        int beatTime = Integer.parseInt(timeSpinner.getValue().toString());
        int cols = division * beats;        
//        if(cols > 120){
//            cols = 120;
//            beats = 120;
//            division = 1;
//            divisionComboBox.setSelectedIndex(0);
//        }
       int cells = cols * 5;   // all table cells
       Pattern pat = new Pattern(cells);
       int sourceEvents = currentPattern.getEventList().size();
       int targetEvents = pat.getEventList().size();
       for(int i = 0; i < targetEvents && i < sourceEvents; i++){
           pat.addEvent(i, currentPattern.getEventAt(i));
       }
       pat.setBeats(beats);
       pat.setDivision(division);
       pat.setBeatTime(beatTime);
       currentPattern = pat;
       ((RhythmPanel)rhythmPanel).setCurrentPattern(currentPattern);
       ((RhythmPanel)rhythmPanel).makeLabels();
    
    }
    
    
    private void setRhythmTableModel(){
       
        int division = Integer.parseInt(divisionComboBox.getSelectedItem().toString());
        int beats = Integer.parseInt(numberOfBeats.getSelectedItem().toString());
        int beatTime = Integer.parseInt(timeSpinner.getValue().toString());
        int cols = division * beats;        
        if(cols > 120){
            cols = 120;
            beats = 120;
            division = 1;
            divisionComboBox.setSelectedIndex(0);
        }
       int cells = cols * 5;   // all table cells
       currentPattern = new Pattern(cells);
       currentPattern.setBeats(beats);
       currentPattern.setDivision(division);
       currentPattern.setBeatTime(beatTime);
       ((RhythmPanel)rhythmPanel).setCurrentPattern(currentPattern);
       ((RhythmPanel)rhythmPanel).makeLabels();
              
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
            
        });
        
        
        
    }
    
    // window closing handler
        WindowListener wl = new WindowAdapter(){
            public void windowClosing(WindowEvent e){                
                UsbWriter.deInit();
            }
        };
        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bassGuitarLabel;
    private javax.swing.JLabel beatLabel;
    private javax.swing.JMenuItem choosePattern;
    private javax.swing.JButton clearPatternButton;
    private javax.swing.JMenuItem clearSequence;
    private javax.swing.JComboBox<String> divisionComboBox;
    private javax.swing.JLabel drumPatternLabel;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fileMenuAdd;
    private javax.swing.JMenuItem fileMenuClose;
    private javax.swing.JMenuItem fileMenuOpen;
    private javax.swing.JMenuItem fileMenuSave;
    private javax.swing.JMenuItem insertOneAfter;
    private javax.swing.JMenuItem insertOneBefore;
    private javax.swing.JPopupMenu insertPatternPopup;
    private javax.swing.JComboBox<String> instrumentComboBox;
    private javax.swing.JLabel instrumentLabel;
    private javax.swing.JLabel leftFootLabel;
    private javax.swing.JLabel leftHandLabel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JComboBox<String> noteSelectComboBox;
    private javax.swing.JComboBox<String> numberOfBeats;
    private javax.swing.JLabel octaveLabel;
    private javax.swing.JComboBox<String> octaveSelectComboBox;
    private javax.swing.JSeparator paneSeparator;
    private javax.swing.JPanel patternGroupPanel;
    private javax.swing.JButton playPatternButton;
    private javax.swing.JButton playSequenceButton;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JMenuItem removePattern;
    private javax.swing.JSpinner repeatPatternSpinner;
    private javax.swing.JLabel resolutionLabel;
    private javax.swing.JPanel rhythmPanel;
    private javax.swing.JLabel rightFootLabel;
    private javax.swing.JLabel rightHandLabel;
    private javax.swing.JButton saveFileButton;
    private javax.swing.JButton savePatternButton;
    private javax.swing.JButton saveSequenceButton;
    private javax.swing.JComboBox selectPatternComboBox;
    private javax.swing.JLabel selectPatternLabel;
    private javax.swing.JComboBox selectSequencePatternComboBox;
    private javax.swing.JScrollPane sequenceScrollPane;
    private javax.swing.JTable sequenceTable;
    private javax.swing.JButton setPatternButton;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JSpinner timeSpinner;
    private javax.swing.JButton usbTransferButton;
    // End of variables declaration//GEN-END:variables

class CustomCellRenderer extends JLabel implements TableCellRenderer {
 
    
  @Override  
  public Component getTableCellRendererComponent(JTable table,Object value,boolean isSelected,boolean hasFocus,int row,int column) {
    
    //Component c = super.getTableCellRendererComponent(table,value,isSelected, hasFocus,row, column);
    //JLabel lab = (JLabel)super.getTableCellRendererComponent(table,value,isSelected, hasFocus,row, column);
    
    
    if(table.getName().equals("patternTable")){
        int rowCount = table.getRowCount();
        int listIndex = column * rowCount + row;
        MidiInstrument instrument = currentPattern.getEventAt(listIndex).getMidiInstrument();
        if( instrument != MidiInstrument.NONE){
            //instrument = currentPatternData[row][column].getMidiInstrument();           
            setOpaque(true);
            setBackground(instrument.getBackground());  
            setToolTipText(instrument.getName());
            
        }
        
        else{ 
            setOpaque(false);
            setBackground(Color.white);
            setToolTipText(MidiInstrument.NONE.getName());
            
         }
    }
    
        else if(table.getName().equals("sequenceTable")){
            if(value != null){
                setHorizontalAlignment(CENTER);
                setText(value.toString());
                setOpaque(true);
                setBackground(Color.yellow);
            }
            else{
                setOpaque(false);
                setBackground(Color.white);
                setText("");
            }
        }
    
    
    return this;
  }
}



}



